# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 02 Jul 2025 00:10:17 +0200
*               @ALL          0
*               @user         8
