# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 02 Jul 2025 00:10:17 +0200
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

dmanassa:$2y$10$vGrXPmQV98tndr8T8W2jDuLJYQQ/dmEZqYUsZZD6WuwKHuL9yaNWy:Damien:damien.manassa@oregonstate.edu:admin,user
